name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'react-app/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Project
        run: npm run build

      - name: Start Preview Server
        run: npm run preview -- --port 5173 &

      - name: Install wait-on
        run: npm install --global wait-on

      - name: Wait for Server
        run: wait-on http://localhost:5173 --timeout 120000

      # Copy package files from react-app to the repository root (so that npm ci and Cypress can find them)
      - name: Copy Package Files to Root
        run: |
          cp package.json ../
          cp package-lock.json ../

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v4
        with:
          config-file: react-app/cypress.config.js
          start: ""
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
