name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        # Set the working directory to your React application folder
        working-directory: react-app


    steps:
      # 1. Checkout the repository.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install dependencies.
      - name: Install Dependencies
        run: npm ci

      # 4. Run ESLint for static code analysis.
      - name: Run ESLint
        run: npm run lint


      # 5. Run Unit Tests via Vitest.
      - name: Run Unit Tests
        run: npm run test:unit

      # 6. Build the project.
      - name: Build Project
        run: npm run build


      # 7. Start the preview server on port 5173 in the background.
      - name: Start Preview Server
        run: npm run preview -- --port 5173 &

      # 8. Wait for the preview server to be ready.

      - name: Install wait-on
        run: npm install --global wait-on

      - name: Wait for Server
        run: wait-on http://localhost:5173 --timeout 120000


      # 9. Run Cypress end-to-end tests.
      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v4
        with:
          # The preview server is already running, so we leave start empty.
          start: ""
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
