name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  unit-tests:
    name: Jest Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test  # This will run "jest --coverage"

  e2e-tests:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Run app in preview mode
        run: |
          npm run preview &
          # Wait a few seconds to ensure the preview is fully up
          sleep 5

      - name: Run Cypress Tests
        run: npm run cypress
