name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:

        working-directory: react-app # Set working directory to react-app


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: react-app          # Checkout into react-app directory

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'       # Match your Node.js version
        

      # 3. Install dependencies.
      - name: Install Dependencies
        run: npm ci

      # 4. Run ESLint for static code analysis.
      - name: Run ESLint
        run: npm run lint


      # 5. Run Unit Tests via Vitest.
      - name: Run Unit Tests
        run: npm run test:unit

      # 6. Build the project.
      - name: Build Project
        run: npm run build

      # 7. Start the preview server on port 5173 in the background.
      - name: Start Preview Server
        run: npm run preview -- --port 5173 &

      # 8. Wait for the preview server to be ready.

      - name: Install wait-on
        run: npm install --global wait-on

      - name: Wait for Server
        run: wait-on http://localhost:5173 --timeout 120000



      # 9. Run Cypress E2E tests.
      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v4
        with:
          # The preview server is already running, so no need to start it here.
          start: ""
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120