name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  unit-tests:
    name: Jest Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

  e2e-tests:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start application in preview mode
        run: |
          npm run preview &
          sleep 5

      - name: Run Cypress tests
        run: npm run cypress

